services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

        bind:
            $projectDir: '%kernel.project_dir%'

    Barth\SimpleConfigBundle\:
        resource: '../../{Service,Twig,NameConverter}/*'

    Barth\SimpleConfigBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
